### ISSUE TITLE
Umfpack in trilinos

### ISSUE THREAD

**Issue by cpraveen** [davydden/homebrew-dealiisuite#11]
Hi,
Is it possible to provide umfpack through trilinos. This is possible in homebrew where it links with suitesparse. But I dont see suitesparse being included here.

**Comment by davydden** [comment]
currently we don't install suitesparse ( don't recall the reason), i will give it a quick try to see if it works on my CentOS...

**Comment by davydden** [comment]
`suitesparse` worked, reinstalling `trilinos` to check that it works as well...

**Comment by davydden** [comment]
try installing from https://github.com/davydden/homebrew-dealiisuite/pull/12

**Comment by davydden** [comment]
we merged this PR, so you can just update and install from master.

**Comment by cpraveen** [comment]
Thanks a lot. I am trying to install trilinos. It automatically installed suitesparse. But

```
==> Installing davydden/dealiisuite/trilinos
Error: davydden/dealiisuite/trilinos cannot be built with any available compilers.
```

I have

```
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 
```

Do I need a newer version ?

**Comment by davydden** [comment]
I think yes, that's because Trilinos needs C11 support for some of the core packages, and we try to make sure it's there in these lines:  https://github.com/davydden/homebrew-dealiisuite/blob/master/trilinos.rb#L88-L89

i suppose some internal checks in Homebrew/Linuxbrew fail then.
GCC `4.8` works for me.

You can try commenting out https://github.com/davydden/homebrew-dealiisuite/blob/master/trilinos.rb#L89 and https://github.com/davydden/homebrew-dealiisuite/blob/master/trilinos.rb#L91  and give it a try.

If you did this

```
ln -s `which gcc` $HOMEBREW_PREFIX/bin/gcc-`gcc -dumpversion |cut -d. -f1,2`
ln -s `which g++` $HOMEBREW_PREFIX/bin/g++-`g++ -dumpversion |cut -d. -f1,2`
ln -s `which gfortran` $HOMEBREW_PREFIX/bin/gfortran-`gfortran -dumpversion |cut -d. -f1,2`
```

and all `gcc --version`, `g++ --version` and `gfortran --version` work you should be able to install trilinos but it will disable some packages due to absence of c11 in your version of compiler. But I am not sure if deal.ii will have enough trilinos packages. Give it a try and let us know.

**Comment by davydden** [comment]
@cpraveen any luck?

**Comment by davydden** [comment]
no response, close issue for now. Feel free to re-open if it is not resolved yet.

**Comment by cpraveen** [comment]
Sorry for not getting to this. I need Sacado for my work. So I was upgrading the compiler to 4.8.2. I have to reinstall the whole thing now. I will report if there are any issues.
